/**
 * Seed data for the mock service layer (shaped like API Rev 2). Replaced by the
 * real API later (flip USE_MOCK in service.ts). Illustrative Cahul civic data.
 */

import type { Author, Comment, Complaint, Notification, Post, User, VerificationRequest } from './types';

const primaria: Author = { id: 'city', fullName: 'Primăria Cahul' };
const ion: Author = { id: 'u1', fullName: 'Ion Popescu' };
const maria: Author = { id: 'u2', fullName: 'Maria V.' };
const andrei: Author = { id: 'u3', fullName: 'Andrei P.' };
const elena: Author = { id: 'u4', fullName: 'Elena C.' };

export const mockUser: User = {
  id: 'u1',
  email: 'ion.popescu@exemplu.md',
  fullName: 'Ion Popescu',
  role: 'CITIZEN',
  locale: 'ro',
  createdAt: '2026-07-01T09:00:00Z',
  // Starts unverified so the participation gate is visible from the first screen.
  verification: 'UNVERIFIED',
};

/** The primărie operator. Real login returns whichever user the token belongs to. */
export const mockAdmin: User = {
  id: 'a1',
  email: 'primaria@cahul.md',
  fullName: 'Primăria Cahul',
  role: 'ADMIN',
  locale: 'ro',
  createdAt: '2026-06-01T09:00:00Z',
  verification: 'VERIFIED',
};

export const mockPosts: Post[] = [
  {
    id: 'p1',
    title: 'Reorganizarea traseului de microbuz nr. 5',
    body: 'Primăria propune modificarea traseului pentru a acoperi sectorul Centru și zona gării. Spuneți-ne părerea până pe 12 august.',
    type: 'HEARING',
    lang: 'ro',
    status: 'OPEN',
    verdict: null,
    closedAt: null,
    author: primaria,
    likesCount: 42,
    dislikesCount: 5,
    commentsCount: 3,
    myReaction: null,
    createdAt: '2026-08-01T10:00:00Z',
    deadline: '2026-08-12T23:59:00Z',
  },
  {
    id: 'p2',
    title: 'Amenajarea parcului de pe str. Ștefan cel Mare',
    body: 'Consultare privind amenajarea spațiului verde: alei, bănci, iluminat și un loc de joacă pentru copii.',
    type: 'DRAFT_DECISION',
    lang: 'ro',
    status: 'CLOSED',
    verdict: 'Proiect aprobat. Lucrările încep în septembrie 2026, cu buget alocat pentru alei, iluminat și un loc de joacă.',
    closedAt: '2026-07-20T10:00:00Z',
    author: primaria,
    likesCount: 88,
    dislikesCount: 3,
    commentsCount: 0,
    myReaction: 'LIKE',
    createdAt: '2026-07-05T10:00:00Z',
  },
  {
    id: 'p3',
    title: 'Bugetul civic 2026 — propuneri',
    body: 'Alege cum sunt cheltuiți 2 milioane de lei din bugetul orașului. Propune și votează proiecte pentru cartierul tău.',
    type: 'DISCUSSION',
    lang: 'ro',
    status: 'OPEN',
    verdict: null,
    closedAt: null,
    author: primaria,
    likesCount: 31,
    dislikesCount: 2,
    commentsCount: 0,
    myReaction: null,
    createdAt: '2026-08-03T10:00:00Z',
    deadline: '2026-08-18T23:59:00Z',
  },
  {
    id: 'p4',
    title: 'Reabilitarea trotuarelor din sectorul Centru',
    body: 'Program de reabilitare a trotuarelor pe principalele străzi. Indicați zonele prioritare.',
    type: 'HEARING',
    lang: 'ro',
    status: 'OPEN',
    verdict: null,
    closedAt: null,
    author: primaria,
    likesCount: 19,
    dislikesCount: 1,
    commentsCount: 0,
    myReaction: null,
    createdAt: '2026-08-05T10:00:00Z',
    deadline: '2026-08-25T23:59:00Z',
  },
];

export const mockComments: Record<string, Comment[]> = {
  p1: [
    {
      id: 'c0',
      postId: 'p1',
      parentId: null,
      author: primaria,
      text: 'Mulțumim pentru propuneri. Consultarea rămâne deschisă până pe 20 august, iar traseul final va fi aprobat în ședința Consiliului local.',
      canDelete: false,
      likesCount: 12,
      dislikesCount: 0,
      myReaction: null,
      repliesCount: 0,
      createdAt: '2026-08-03T09:00:00Z',
      replies: [],
    },
    {
      id: 'c1',
      postId: 'p1',
      parentId: null,
      author: maria,
      text: 'Traseul nou ar ajuta mult zona gării.',
      canDelete: false,
      likesCount: 4,
      dislikesCount: 0,
      myReaction: null,
      repliesCount: 1,
      createdAt: '2026-08-01T12:00:00Z',
      replies: [
        {
          id: 'c2',
          postId: 'p1',
          parentId: 'c1',
          author: primaria,
          text: 'Mulțumim, vom analiza acoperirea zonei gării.',
          canDelete: false,
          likesCount: 1,
          dislikesCount: 0,
          myReaction: null,
          repliesCount: 0,
          createdAt: '2026-08-01T13:00:00Z',
          replies: [],
        },
      ],
    },
    {
      id: 'c3',
      postId: 'p1',
      parentId: null,
      author: elena,
      text: 'Sper să păstreze cursele de dimineață devreme.',
      canDelete: false,
      likesCount: 2,
      dislikesCount: 0,
      myReaction: null,
      repliesCount: 0,
      createdAt: '2026-08-02T08:30:00Z',
      replies: [],
    },
    {
      id: 'c4',
      postId: 'p1',
      parentId: null,
      author: andrei,
      text: 'De acord, dar și stația de lângă piață.',
      canDelete: true,
      likesCount: 1,
      dislikesCount: 0,
      myReaction: null,
      repliesCount: 0,
      createdAt: '2026-08-02T09:10:00Z',
      replies: [],
    },
  ],
};

export const mockComplaints: Complaint[] = [
  {
    id: 'f1',
    title: 'Groapă mare pe str. Independenței',
    description: 'În dreptul casei nr. 24 este o groapă adâncă, periculoasă pentru mașini.',
    category: 'ROADS',
    address: 'str. Independenței 24',
    lat: 45.9083,
    lng: 28.1949,
    photoUrl: null,
    status: 'IN_PROGRESS',
    adminResponse: null,
    author: ion,
    createdAt: '2026-08-02T09:00:00Z',
    updatedAt: '2026-08-04T14:00:00Z',
  },
  {
    id: 'f2',
    title: 'Felinar stins pe str. Mihai Eminescu',
    description: 'De o săptămână nu funcționează iluminatul pe toată strada.',
    category: 'LIGHTING',
    address: 'str. Mihai Eminescu',
    lat: 45.9101,
    lng: 28.2005,
    photoUrl: null,
    status: 'RESOLVED',
    adminResponse: 'Felinarul a fost reparat pe 5 august. Mulțumim pentru sesizare.',
    author: ion,
    createdAt: '2026-07-28T18:00:00Z',
    updatedAt: '2026-08-05T11:00:00Z',
  },
  {
    id: 'f3',
    title: 'Program neclar la microbuzul nr. 3',
    description: 'Orarul afișat nu corespunde cu realitatea la orele de vârf.',
    category: 'TRANSPORT',
    address: null,
    lat: null,
    lng: null,
    photoUrl: null,
    status: 'NEW',
    adminResponse: null,
    author: ion,
    createdAt: '2026-08-06T07:30:00Z',
    updatedAt: '2026-08-06T07:30:00Z',
  },
];

/** The primărie's review queue. Ion's own request is appended when he submits. */
export const mockVerifications: VerificationRequest[] = [
  {
    id: 'v1',
    user: maria,
    idnp: '2004008123456',
    address: 'str. Independenței 12, ap. 4',
    status: 'PENDING',
    reason: null,
    createdAt: '2026-08-06T15:20:00Z',
  },
  {
    id: 'v2',
    user: andrei,
    idnp: '2003005998877',
    address: 'str. Victoriei 3',
    status: 'PENDING',
    reason: null,
    createdAt: '2026-08-07T08:05:00Z',
  },
  {
    id: 'v3',
    user: elena,
    idnp: '2001002445566',
    address: 'str. Ștefan cel Mare 41',
    status: 'VERIFIED',
    reason: null,
    createdAt: '2026-08-01T11:00:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    kind: 'PARSED',
    source: 'premier_energy',
    title: null,
    body: null,
    payload: {
      workType: 'lucrari_programate',
      url: 'https://premierenergydistribution.md/ro/',
      segments: [
        { streets: 'str. Independenței, str. Victoriei', timeStart: '09:00', timeEnd: '15:00', reason: 'lucrări de mentenanță' },
      ],
    },
    eventDate: '2026-08-09',
    isRead: false,
    createdAt: '2026-08-07T08:00:00Z',
  },
  {
    id: 'n2',
    kind: 'COMPLAINT_STATUS',
    source: null,
    title: null,
    body: null,
    payload: {
      complaintId: 'f1',
      complaintTitle: 'Groapă mare pe str. Independenței',
      status: 'IN_PROGRESS',
      adminResponse: null,
    },
    eventDate: null,
    isRead: false,
    createdAt: '2026-08-04T14:00:00Z',
  },
  {
    id: 'n3',
    kind: 'MANUAL',
    source: null,
    title: 'Ședință publică — bugetul 2026',
    body: 'Vă invităm la ședința publică de consultare a bugetului pe 15 august, ora 17:00, la sediul primăriei.',
    payload: null,
    eventDate: '2026-08-15',
    isRead: true,
    createdAt: '2026-08-06T10:00:00Z',
  },
];
